# Generated by Django 2.2.7 on 2020-01-01 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convener',
            fields=[
                ('vp_id', models.AutoField(primary_key=True, serialize=False)),
                ('vp_name', models.CharField(default='', max_length=200)),
                ('vp_mobile', models.CharField(default='', max_length=13)),
                ('vp_email', models.CharField(default='', max_length=100)),
                ('vp_profession', models.CharField(default='', max_length=500)),
                ('vp_work', models.CharField(max_length=500)),
                ('vp_start_time', models.TimeField()),
                ('vp_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('v_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_name', models.CharField(default='', max_length=200)),
                ('v_mobile', models.CharField(default='', max_length=13)),
                ('v_email', models.CharField(default='', max_length=100)),
                ('v_perpose', models.CharField(default='', max_length=100)),
                ('v_collage', models.CharField(default='', max_length=100)),
                ('v_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_login_time', models.DateTimeField(auto_now_add=True)),
                ('v_logout_time', models.TimeField()),
                ('v_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.Visitor')),
                ('vp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vm.Convener')),
            ],
        ),
    ]
