# Generated by Django 2.2.7 on 2020-01-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0002_remove_visitor_v_vp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='v_collage',
            new_name='v_address',
        ),
    ]
