# Generated by Django 2.2.7 on 2020-02-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0003_auto_20200104_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='v_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.Visitor'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='vp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm.Convener'),
        ),
    ]
