# Generated by Django 2.2.7 on 2020-02-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0005_visitor_v_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convener',
            old_name='vp_work',
            new_name='vp_department',
        ),
    ]
